In [100]:
import pandas as pd

In [101]:
match=pd.read_csv('../datasets/match.csv')
player=pd.read_csv('../datasets/player_match.csv')

In [102]:
print(match.columns)

Index(['match_sk', 'match_id', 'team1', 'team2', 'match_date', 'season_year',
       'venue_name', 'city_name', 'country_name', 'toss_winner',
       'match_winner', 'toss_name', 'win_type', 'outcome_type', 'manofmach',
       'win_margin', 'country_id'],
      dtype='object')


In [103]:
print(player.columns)

Index(['player_match_sk', 'playermatch_key', 'match_id', 'player_id',
       'player_name', 'dob', 'batting_hand', 'bowling_skill', 'country_name',
       'role_desc', 'player_team', 'opposit_team', 'season_year',
       'is_manofthematch', 'age_as_on_match', 'isplayers_team_won',
       'batting_status', 'bowling_status', 'player_captain', 'opposit_captain',
       'player_keeper', 'opposit_keeper'],
      dtype='object')


## Data Cleaning and Preparing

In [104]:
match_columns=match[['match_id', 'match_winner', 'manofmach']].copy()
player_columns=player[['match_id','player_name','player_team']].copy()

In [107]:
match_columns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 637 entries, 0 to 636
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   match_id      637 non-null    int64 
 1   match_winner  634 non-null    object
 2   manofmach     633 non-null    object
dtypes: int64(1), object(2)
memory usage: 15.1+ KB


Let's remove all the rows that has null values in manofmach column

In [108]:
match_columns=match_columns.dropna(subset=['manofmach'])

In [97]:
match_columns['match_winner'].value_counts()

match_winner
Mumbai Indians                 91
Chennai Super Kings            79
Kolkata Knight Riders          77
Royal Challengers Bangalore    73
Kings XI Punjab                70
Rajasthan Royals               63
Delhi Daredevils               62
Sunrisers Hyderabad            42
Deccan Chargers                29
Rising Pune Supergiants        15
Gujarat Lions                  13
Pune Warriors                  12
Kochi Tuskers Kerala            6
tied                            1
Name: count, dtype: int64

There is one match that ended in a tie; however, the "Man of the Match" trophy was awarded to a specific player. We will remove this as it has no impact on the match result.

In [111]:
match_columns=match_columns.copy()
match_columns.drop(match_columns[match_columns['match_winner'] == 'tied'].index, inplace=True)

In [114]:
match_player = pd.merge(
    match_columns,
    player_columns[['match_id', 'player_name', 'player_team']],  
    left_on=['match_id', 'manofmach'],  
    right_on=['match_id', 'player_name'],  
    how='left' 
)

In [115]:
match_player

match_id                 match_winner         manofmach      player_name  \
0      335987        Kolkata Knight Riders       BB McCullum      BB McCullum   
1      335988          Chennai Super Kings        MEK Hussey       MEK Hussey   
2      335989             Delhi Daredevils       MF Maharoof      MF Maharoof   
3      335990  Royal Challengers Bangalore        MV Boucher       MV Boucher   
4      335991        Kolkata Knight Riders         DJ Hussey        DJ Hussey   
..        ...                          ...               ...              ...   
627   1082646  Royal Challengers Bangalore          HV Patel         HV Patel   
628   1082647      Rising Pune Supergiants  Wasington Sundar              NaN   
629   1082648        Kolkata Knight Riders   NM Coulter-Nile  NM Coulter-Nile   
630   1082649               Mumbai Indians         KV Sharma        KV Sharma   
631   1082650               Mumbai Indians         KH Pandya        KH Pandya   

                     player_team  
0          Kolkata Knight Riders  
1            Chennai Super Kings  
2               Delhi Daredevils  
3    Royal Challengers Bangalore  
4          Kolkata Knight Riders  
..                           ...  
627  Royal Challengers Bangalore  
628                          NaN  
629        Kolkata Knight Riders  
630               Mumbai Indians  
631               Mumbai Indians  

[632 rows x 5 columns]

In [116]:
match_player.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 632 entries, 0 to 631
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   match_id      632 non-null    int64 
 1   match_winner  632 non-null    object
 2   manofmach     632 non-null    object
 3   player_name   630 non-null    object
 4   player_team   630 non-null    object
dtypes: int64(1), object(4)
memory usage: 24.8+ KB


In [123]:
match_player[match_player['player_name'].isna()]

match_id             match_winner         manofmach player_name  \
584   1082601    Kolkata Knight Riders            Narine         NaN   
628   1082647  Rising Pune Supergiants  Wasington Sundar         NaN   

    player_team  
584         NaN  
628         NaN

In [127]:
player_columns[player_columns['match_id'] == 1082601 ]
player_columns[player_columns['match_id'] == 1082647 ]

match_id        player_name              player_team
13904   1082647           PA Patel           Mumbai Indians
13905   1082647           MS Dhoni  Rising Pune Supergiants
13906   1082647          RG Sharma           Mumbai Indians
13907   1082647          AM Rahane  Rising Pune Supergiants
13908   1082647          MK Tiwary  Rising Pune Supergiants
13909   1082647          KV Sharma           Mumbai Indians
13910   1082647         SL Malinga           Mumbai Indians
13911   1082647          AT Rayudu           Mumbai Indians
13912   1082647         KA Pollard           Mumbai Indians
13913   1082647       DT Christian  Rising Pune Supergiants
13914   1082647          SPD Smith  Rising Pune Supergiants
13915   1082647         JD Unadkat  Rising Pune Supergiants
13916   1082647          JJ Bumrah           Mumbai Indians
13917   1082647        LMP Simmons           Mumbai Indians
13918   1082647          HH Pandya           Mumbai Indians
13919   1082647     MJ McClenaghan           Mumbai Indians
13920   1082647          SN Thakur  Rising Pune Supergiants
13921   1082647          KH Pandya           Mumbai Indians
13922   1082647            A Zampa  Rising Pune Supergiants
13923   1082647        LH Ferguson  Rising Pune Supergiants
13924   1082647        RA Tripathi  Rising Pune Supergiants
13925   1082647  Washington Sundar  Rising Pune Supergiants

this was due to the different naming in 2 tables. Now let's add the value of player_name and player_team column with match_id=1082601 and 1082647

In [128]:
match_player.loc[match_player['match_id'] == 1082601, ['player_name', 'player_team']] = ['Narine', 'Kolkata Knight Riders']
match_player.loc[match_player['match_id'] == 1082647, ['player_name', 'player_team']] = ['Wasington Sundar', 'Rising Pune Supergiants']

In [130]:
match_player

match_id                 match_winner         manofmach  \
0      335987        Kolkata Knight Riders       BB McCullum   
1      335988          Chennai Super Kings        MEK Hussey   
2      335989             Delhi Daredevils       MF Maharoof   
3      335990  Royal Challengers Bangalore        MV Boucher   
4      335991        Kolkata Knight Riders         DJ Hussey   
..        ...                          ...               ...   
627   1082646  Royal Challengers Bangalore          HV Patel   
628   1082647      Rising Pune Supergiants  Wasington Sundar   
629   1082648        Kolkata Knight Riders   NM Coulter-Nile   
630   1082649               Mumbai Indians         KV Sharma   
631   1082650               Mumbai Indians         KH Pandya   

          player_name                  player_team  
0         BB McCullum        Kolkata Knight Riders  
1          MEK Hussey          Chennai Super Kings  
2         MF Maharoof             Delhi Daredevils  
3          MV Boucher  Royal Challengers Bangalore  
4           DJ Hussey        Kolkata Knight Riders  
..                ...                          ...  
627          HV Patel  Royal Challengers Bangalore  
628  Wasington Sundar      Rising Pune Supergiants  
629   NM Coulter-Nile        Kolkata Knight Riders  
630         KV Sharma               Mumbai Indians  
631         KH Pandya               Mumbai Indians  

[632 rows x 5 columns]

In [139]:
match_player['player_impact']=(match_player['match_winner'] == match_player['player_team']).astype(int)